help = {"weights": "WEIGHTS initial weights path",
  "cfg" :"CFG model.yaml path",
  "data": "DATA dataset.yaml path",
  "hyp": "HYP hyperparameters path",
  "epochs": "EPOCHS total training epochs",
  "batch-size": "BATCH_SIZE total batch size for all GPUs, -1 for autobatch",
  "img":"IMGSZ train, val image size (pixels)",
  "rect": "rectangular training",
  "resume": "[RESUME] resume most recent training",
  "nosave": "only save final checkpoint",
  "noval": "only validate final epoch",
  "noautoanchor": "disable AutoAnchor",
  "noplots": "save no plot files",
  "evolve": "[EVOLVE] evolve hyperparameters for x generations",
  "bucket": "BUCKET gsutil bucket",
  "cache": "[CACHE] image cache ram/disk",
  "image-weights": "use weighted image selection for training",
  "device DEVICE": "cuda device, i.e. 0 or 0,1,2,3 or cpu",
  "multi-scale": "vary img-size +/- 50%",
  "single-cls": "train multi-class data as single-class",
  "optimizer": "{SGD,Adam,AdamW} optimizer",
  "sync-bn": "use SyncBatchNorm, only available in DDP mode",
  "workers": "WORKERS max dataloader workers (per RANK in DDP mode)",
  "project": "PROJECT save to project/name",
  "name": "NAME save to project/name",
  "exist-ok": "existing project/name ok, do not increment",
  "quad": "quad dataloader",
  "cos-lr": "cosine LR scheduler",
  "label-smoothing": "LABEL_SMOOTHING Label smoothing epsilon",
  "patience": "PATIENCE EarlyStopping patience (epochs without improvement)",
  "freeze": "FREEZE [FREEZE ...] Freeze layers: backbone=10, first3=0 1 2",
  "save-period": "SAVE_PERIOD Save checkpoint every x epochs (disabled if < 1)",
  "seed": "SEED Global training seed",
  "local_rank": "LOCAL_RANK Automatic DDP Multi-GPU argument, do not modify",
  "entity": "ENTITY Entity",
  "upload_dataset": "[UPLOAD_DATASET] Upload data, val option",
  "bbox_interval": "BBOX_INTERVAL Set bounding-box image logging interval",
  "artifact_alias": "ARTIFACT_ALIAS Version of dataset artifact to use"
  }